#!/usr/bin/python
import subprocess
import sys

DESIRED_BRANCH = 'master'
DESIRED_REMOTE = 'gh-pages'

def err_with_msg(msg):
    print 'Error: {}'.format(msg)
    sys.exit(1)

def deploy():
    print subprocess.check_output(['git', 'push', 'origin', '{}:{}'.format(DESIRED_BRANCH, DESIRED_REMOTE)]).rstrip()

curr_branch = subprocess.check_output('git symbolic-ref --short -q HEAD'.split()).rstrip()
if curr_branch != DESIRED_BRANCH:
    err_with_msg('Must be on {}'.format(DESIRED_BRANCH))

deploy()



